dist: xenial
language: node_js
node_js:
- node

stages:
  - test
  - name: deploy
    if: branch IN (master, PTH-13950-auth)

jobs:
  include:
  - stage: test
    services:
    - mongodb
    env:
    - NODE_ENV=test
    - MONGO_DSN=mongodb://localhost:27017/ptah-test
    - SERVER_PORT=3001
    - MOCK_SERVER_PORT=3002
    - MAILCHIMP_METADATA_URL=http://localhost:3002/oauth2/metadata
    - PASSWORD_SECRET=test
    - AUTH_TOKEN_SECRET=test
    - RESTORE_PASSWORD_SECRET=test
    - CONFIRM_EMAIL_SECRET=test
    - GOOGLE_AUTH_CLIENT_ID=test
    - GOOGLE_AUTH_CLIENT_SECRET=test
    - LANDINGS_PUBLISHING_HOST=ptah.com
    install:
    - npm install -g codecov nyc mocha
    - npm ci
    script:
    - npm run tests:migrations
    - npm run tests:generator
    - nyc --reporter=lcovonly mocha --exit --timeout 8000 ./test/index.js
    - codecov
  - stage: deploy
    services: docker
    install: true
    script:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker run -it
      -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN
      -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG
      -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger;
      fi

notifications:
  slack:
    secure: QYbVkuWqQLYVN8UfqscOg3mnBxS5rXvszKdFWrpXM4r6bJZy77ip0OCDSlzWm6X1KOWpAtlSzIZRJqrIGdHMVGvxOaeoGFf/pHXwNx7BKIUI05EDsm0EfTB2YX6IpU5Lg5SzmVm42RfnNYUIx+AeTs+/IsL12wV7Xp1rnNhD4vXMnovf3SLLOR7+iy3jud9x365G771HtBlIM5FnvgvYeepqzNUFPOu4b2Dg8WO3/nsfpCSP1ovzoThuEGbo5mQQw4fBm+V46esxY5KGxeBHaKE7RWru5bEipaV0KLCJosCJv7HVuzsRGqtRrzOtpZY0ETHuPBoVvhDjas/+CMQfPdRk95y2yxy1wnDcb3cdTKzAww4E7TDhGBpyeZAxkEJKFXumHUdIjinUyQk+fkLBxC245VjqgIepCS4TZ8gtLd6/0T2xZU2Q4IiqkkyF34cnHHCxTgFCxlq5kZHskf/4ZJlUKRF8iyGLJGuzaI8lpIVKqjuFxW30mR+Z7Ee3/XfOuN6slyFn/rGSFomiOVFEMXxx5cUZ9q794E9hR8mvbzUbtrBZBYr692Sww6XXmzbLJQN8mFxKLBZLy3C0qbOz4ui4tdq62wenPs50XAzqwGMayiqrohhyIKIVfmyaqznbfQu15AFEokKn8fNYphw3lG8eXymOEopkt1pBPXy5PqE=
